services:
  # Backend de Blueprints con seguridad JWT (Lab 4), construido desde su repositorio
  backend:
    build:
      context: https://github.com/JoshQ10/LAB04_ARSW_Joshua-David-Quiroga-Landazabal.git#main
    ports:
      - '8080:8080'

  web:
    build:
      context: .
      args:
        VITE_USE_MOCK: 'false'
    environment:
      BACKEND_URL: http://backend:8080
    ports:
      - '5173:80'
    depends_on:
      - backend
